
default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 username: <%= ENV['KLASEKO_USR'] %>
 password: <%= ENV['KLASEKO_PWD'] %>

development:
 <<: *default
 database: <%= ENV['PAYMENTS_CLIENT_DB_NAME'] %>
 host: <%= ENV['PAYMENTS_CLIENT_DB_HOST'] %>
